### ISSUE TITLE
Update QA checklist to capture identified regression

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#192]
**What's the problem this feature will solve?**

Prevent regressions identified in the following issues:
* [x] https://github.com/BICCN/cell-locator/issues/178
* [x] https://github.com/BICCN/cell-locator/issues/179
* [x] https://github.com/BICCN/cell-locator/issues/180
* [x] https://github.com/BICCN/cell-locator/issues/184
* [x] https://github.com/BICCN/cell-locator/issues/185

**Describe the solution you'd like**

To avoid the regressions described in the issue listed above, the file [.github/ISSUE_TEMPLATE/qa-checklist.md](https://github.com/BICCN/cell-locator/blob/master/.github/ISSUE_TEMPLATE/qa-checklist.md) should be updated.

**Alternative Solutions**

Implement self-tests in python.

**Additional context**

NA
