### ISSUE TITLE
Feedback from demo

### ISSUE THREAD

**Issue by jcfr** [BICCN/cell-locator#66]
From @dyf : 

* [x] 1) would be nice to have a tree browser to show/hide areas in the structure ontology (we talked about this awhile ago and de-prioritized it). This is tracked by https://github.com/BICCN/cell-locator/issues/18
* [x] <s>2) when changing yaw/pitch/roll, 'Enter' key should apply. This is tracked by https://github.com/BICCN/cell-locator/issues/67</s>
* [x] 3) the yaw/pitch/roll => angle mappings differ from the coordinate system the lab uses (davidf to ask what this system actually is). Now tracked by https://github.com/BICCN/cell-locator/issues/81
* [x] <s>4) rename S/I (superior, inferior) to D/V (dorsal, ventral)</s>. Fixed in https://github.com/BICCN/cell-locator/commit/60bad5758e21dde2e474b4e75ddb4fc27e2d48b5
* [x] <s>5) support zoom on the annotation/left panel (maybe r-click + drag?). This is tracked by https://github.com/BICCN/cell-locator/issues/67</s>. Fixed in https://github.com/BICCN/cell-locator/commit/cccf74d9c747e6a0c147004dac3d223914a6d355
* [x] <s>6) range slider to adjust contrast of grayscale CCF background (lower, upper). This is tracked by https://github.com/BICCN/cell-locator/issues/69</s>. Fixed in https://github.com/BICCN/cell-locator/pull/77
* [x] <s>7) when saving, if you don't type .json, the file doesn't save and there isn't an error message (auto-append .json if no extension?)</s>. Fixed in b0e989616623d510fe2fb3c0a83baadad23d8e35
* [x] <s>8) need better title on save dialog when clicking "+New" -- unclear if saving current annotation or naming new one.  ("New Annotation File Name"?)</s>. Fixed in https://github.com/BICCN/cell-locator/commit/240df3fbadc623bf857b42141bc3644208ca8826
* [x] <s>9) When creating a new annotation, leave the camera/slice positions alone (better workflow for pinning multiple cells to the same slice). This is tracked by https://github.com/BICCN/cell-locator/issues/70</s>
* [x] <s>10) when clicking "Reset", reset camera position as well. This is tracked by https://github.com/BICCN/cell-locator/issues/71</s>
* [x] <s>11) splash screen appears, disappears for awhile, then reappears</s>. Fixed in https://github.com/BICCN/cell-locator/commit/89f48f580f01cb692fd2a8bf79816a6def857d1c
* [x] <s>12) console window and app window have different icons (white BG vs transparent BG)</s>. Fixed in [BICCN/cell-locator@3c0ee3d](https://github.com/BICCN/cell-locator/commit/3c0ee3d494a10853d7670ec7251c36186aa467bd). Note: Next installer will have the windows console disabled.
